### ISSUE TITLE
[Question] Possible to install chimera in console/server mode only ?

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/chimera-live#11]
I'm trying to install chimera in purely console/server mode using `qemu-system-aarch64`. Is it possible ?

Everything seems to work until here:

```
...
[  OK  ] syslog-ng
[  OK  ] local.target
[  OK  ] pre-network.target
[  OK  ] init-local.target
[  OK  ] dbus-prepare
[  OK  ] dhcpcd
[  OK  ] network.target
[  OK  ] turnstiled
[  OK  ] chrony-dir
[  OK  ] chronyd
[  OK  ] dbus
[  OK  ] polkitd
[  OK  ] elogind
```

After the `elogind` message things seem to "hang". There are no errors.

My guess is the flow shifts to a graphical interface after this point ??

I'm using the `chimera-linux-aarch64-LIVE-20230915-base.iso` image with `u-boot.bin` that I compiled myself.

**Comment by sidkshatriya** [comment]
I've been able to make progress. Adding `-device VGA` to my `qemu-system-aarch64` invocation helps but it would nice to be able to just use and install chimera in pure serial console/server mode.

**Comment by q66** [comment]
the issue you are facing is that there is no getty enabled for your serial console

there is logic in place in the live initramfs that will enable the appropriate getty service based on what you have, since you mention u-boot maybe you are doing something weird?

**Comment by q66** [comment]
see "serial console" in the docs https://chimera-linux.org/docs/installation/boot

**Comment by sidkshatriya** [comment]
I ended up getting sshd working and now I just ssh into the VM. I still have to figure out how to get getty working though. Its not urgent.

Thank you for this really cool project and I've been enjoying chimera. Thank you for the succint and clear documentation too
