### ISSUE TITLE
chimera-bootstrap fails (dns issue)

### ISSUE THREAD

**Issue by smn-1** [chimera-linux/chimera-live#19]
I was installing Chimera for the first time and chimera-bootstrap failed with an error
`WARNING: updating and opening https://repo.chimera-linux.org/current/main: temporary error (try again later)
ERROR: unable to select packages:
chimerautils (no such package):
required by: world[chimerautils]
ERROR: initial installation failed`

This creates the /proc and /var in /mnt/root that need to be removed.

A solution I found was to `rm /etc/resolv.conf` and `touch /etc/resolve.conf` (couldn't write to it even in super user) and add a nameserver (ex: 1.1.1.1) and then restart networkmanager `dinitctl restart networkmanager` I then updated apk `apk update`. Then I could bootstrap again.

Before you enter the chroot, make sure you copy the resolv.conf over `cp /etc/resolv.conf /mnt/root/etc/resolv.conf
`

**Comment by smn-1** [comment]
I tried reinstalling again, just out of curiosity, and I could not replicate the issue. For reference I ran into this issue in the live environment.

**Comment by nekopsykose** [comment]
that error means that dns is broken or some other similar network thing, i.e. it's broken in the live environment and any connections would fail

so the issue could be in the dhcp config for the network you connected to (maybe it gave nonexistent dns servers), etc, and not something that is fixable

**Comment by smn-1** [comment]
Thank you
