### ISSUE TITLE
Error handling when failing to include a kernel or initramfs-tools for iso build

### ISSUE THREAD

**Issue by ghost** [chimera-linux/chimera-live#22]
The `mklive.sh` image requires the user to install a kernel (an obvious need) and `initramfs-tools` (so the hooks can get copied, maybe slightly less obvious of a need) when building an iso. Yet the script will attempt to build whether a user includes the necessary packages to get either of these things (e.g. `base-minimal` only is not sufficient so the user needs to include additional packages like `linux-its` and `initramfs-tools` directly).

This is 100% user error, but it could be slightly more obvious that the user is asking for something not possible (at the same time I recognize that trying to build a custom image/iso is likely advanced usage and a user should be able to mostly recognize this problem themselves by the time they are here - I immediately recognized my mistakes).

It just may be helpful to either briefly document this or have the `mklive.sh` error messages remind the user (e.g. `copy_initramfs || die "failed to copy initramfs files"` -> `copy_initramfs || die "failed to copy initramfs files (is 'initramfs-tools' installed?)"`).

**Comment by q66** [comment]
the mklive-image.sh (which is what you should be using, not raw mklive.sh) includes a kernel for you?

there is no need to manually include initramfs-tools, it gets pulled through base-full-kernel when a kernel is provided

**Comment by ghost** [comment]
I was experimenting with raw `mklive.sh` itself because I wanted to do some experimentation for my own custom iso build (which I wouldn't expect any support for nor open issues about) and bumped into the edge cases above when just seeing what I could do initially (e.g. if I don't want to build the canned options for an iso).

If you really don't want people to call `mklive.sh` itself, it'd probably be advisable to update the readme because I'd say that it is offered as a more advanced option if someone needs more (e.g. perhaps a warning banner or cautionary note at or before "It is also possible to use mklive.sh raw. You can get the full listing of supported arguments like this:")

Again, just noting a possible problem while naively invoking the scripts here like a foolish user might.

**Comment by q66** [comment]
the script already checks whether a kernel is in place (https://github.com/chimera-linux/chimera-live/blob/master/mklive.sh#L195), and if you have a kernel in place, it should pull in initramfs-tools as well

if you're building stuff with base-minimal etc., that's a largely unsupported case and you're on your own anyway (at very least you are expected to 100% know what you are doing)

**Comment by ghost** [comment]
Yes, someone should absolutely understand what they are doing as I've already stated is the case.

But I'm not going to go back on forth on trying to get slightly better documentation here - I think it is lacking but it seems we disagree (I would say that "unable to determine kernel version" itself is an inappropriate message for _no kernel_ as it may imply there is a kernel and the script just couldn't determine what the version is). It is entirely acceptable to expect only advanced users to run these scripts, however the failure cases of the script should be descriptive and/or documented.

I'll go back to what I said before as it seems likely that almost no one should run `mklive.sh`:
> perhaps a warning banner or cautionary note at or before "It is also possible to use mklive.sh raw. You can get the full listing of supported arguments like this:"

FYI:
```
./mklive.sh -p "linux-lts base-minimal"
```
will fail to build even though there is a kernel.
`cp: /home/anon/chimera-live/build/rootfs/usr/share/initramfs-tools/hooks is not a directory`
(^ which is due to a lack of `initramfs-tools`)

**Comment by q66** [comment]
it will fail because base-minimal will not pull in base-full-kernel, but base-minimal is not intended for common/normal use and anyone using it is expected to fully understand the implications
