### ISSUE TITLE
installation of grub on efi hitting 'illegal instruction'  on bare metal x86_64-efi

### ISSUE THREAD

**Issue by bjornstromberg** [chimera-linux/chimera-live#7]
from the verbose output i cant see that it has identified that its a zfs pool yet, and https://chimera-linux.org/docs/installation/zfs only notes about the old grub config caveat finding the root

```
# grub-install --efi-directory=/efi -v
[...]
grub-install: info: no LVM signature found.
grub-install: info: Partition 0 starts from 2048.           [EFI]
grub-install: info: Partition 1 starts from 411648.       [SWAP]
grub-install: info: Partition 2 starts from 21383168.  [ZFS]
grub-install: info: drive = 0.
grub-install: info: the size of hostdisk//dev/sda is 234441648.
Illegal instruction
```

hardware is [Intel C2550 CPU](https://www.intel.com/content/www/us/en/products/sku/77982/intel-atom-processor-c2550-2m-cache-2-40-ghz/specifications.html) so question is if its something like the x86_64 image is built for x86_64-v2 or v3 subarchitecture that is messing with me? or that the old-atom is missing some instruction in the instruction-set?

to rule out zfs as the culprit i'm going to redo the install on ext4 root and see if same issue hits.

used image 'chimera-linux-x86_64-LIVE-20221115-base.iso'

**Comment by bjornstromberg** [comment]
just on a plain ext4 partition installation

```
# grub-install --efi-directory=/efi/
Installing for x86_64-efi platform.
grub-install: error: efibootmgr failed to register the boot entry: No error information.
```

so it seems efibootmgr is the culprit

trying to dump the boot list: (its booted in uefi mode, checked also via ls -l /sys/firmware/efi/efivars) 
```
# efibootmgr 
Illegal instruction
```

the intel nucs i have, pretty much all have messed up uefis (need a correctly named file where windows places the bootloader) but as far as i can remember this server board actually have been working good with gpt + uefi with a bunch of different distros during the years.

well guess i should try a round of dos/mbr table + uefi before fallback to bios to boot

**Comment by bjornstromberg** [comment]
well mbr/bios way works and not efi. 

guess it sufficient go get the box up and running to start rebuilding everything from sources..

**Comment by q66** [comment]
when you hit illegal instruction, it most likely means a ubsan or cfi violation, needs to be fixed or the respective hardening disabled

**Comment by q66** [comment]
can you try with updated packages?

**Comment by bjornstromberg** [comment]
all the packages was updated before trying unless you released new ones to the repo after the first post was made, if so i'll will take a run at it in a few hours after dinner

**Comment by q66** [comment]
yes, i uploaded a new efibootmgr about 10 minutes ago

**Comment by bjornstromberg** [comment]
so updated the package, and booted via live cd (since the uefi vars are not available else..) and from the chroot it still says that its an illegal instruction when running efibootmgr

**Comment by q66** [comment]
fixed: https://github.com/chimera-linux/cports/commit/7baffc8606983a9c3d16711a03dcd3b03caec6cc

**Comment by bjornstromberg** [comment]
yep now efibootmgr works as expected.. 
ah its a bit bashing issue, guess you seen that more then once during the process to port everything...

thanks for the quick fix will continue the quest to test this new toy.. :)
