### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by dfandrich** [chimera-linux/chimera-live#9]
How about supplying a Docker image? That's the quickest and easiest way for most people these days to test out a distribution that whose uniqueness lies in userland.

**Comment by nekopsykose** [comment]
https://docs.docker.com/engine/reference/commandline/import/

**Comment by q66** [comment]
The project already supplies rootfs tarballs, you can just use those (with `docker import <url>` or `FROM scratch; ADD ...` and the likes)

**Comment by dfandrich** [comment]
I'm sure I could do it manually, but I'm also sure you'll find three orders of magnitude more people trying out Chimera if `docker run -it chimera` let them do it compared to those figuring out how to build their own container.

**Comment by nekopsykose** [comment]
it would perhaps be nice and convenient for various reasons (for me included), but popularity contests are probably the worst argument imaginable

**Comment by dfandrich** [comment]
That depends on whether one of Chimera's goals is to have people use it.

**Comment by q66** [comment]
okay, but have you considered that suggesting a pre-alpha project that is a moving target *and* already short on manpower that it maintains *even more stuff* for the sake of a group of people who are not willing to put in the baseline amount of effort (i.e. importing the tarball) and therefore are unlikely to meaningfully contribute might not have been the best of ideas?

**Comment by dfandrich** [comment]
For the record, it looks like someone has done this in the Docker `takano32/chimeralinux` repository.

**Comment by q66** [comment]
`chimeralinux/chimera`

**Comment by dfandrich** [comment]
Awesome!
